# Numpy
- Matrix와 Vector와 같은 Array 연산의 사실상 표준
- 일반 list에 비해 빠르고 메모리가 효율적

In [2]:
import numpy as np

# Array creation
배열 생성 - 하나의 데이터 타입만 배열에 넣을 수 있다

In [3]:
test_array = np.array([1,4,5,8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [4]:
type(test_array[[3]])

numpy.ndarray

In [8]:
test_array = np.array([1,4,5,"8"], float) #데이터 타입이 다 다름 -> float으로 설정해줌
print(test_array)
print(type(test_array[3]))  #float 타입으로 자동 형변환 실시
print(test_array.dtype)   #데이터타입
print(test_array.shape)  #object의 dimension구성

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


# Array shape (matrix)

In [9]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape  #3x4형태

(3, 4)

# Array dtype
- nbyte : ndarray object의 메모리 크기 반환

In [12]:
np.array([[1,2,3], [4.5, "5", "6"]], dtype=np.float32).nbytes   
 #32비트 = 4바이트 -> 6*4바이트

24

#Handling shape

# reshape

In [14]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

array의 사이즈만 같으면 다차원으로 자유롭게 reshape 가능

In [15]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [16]:
np.array(test_matrix).reshape(-1,2).shape
#-1:사이즈를 기반으로 row 개수 선정

(4, 2)

# flatten
다차원의 array를 1차원으로

In [17]:
test_matrix = [[1,2,3,4],[1,2,5,8]],[[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

# indexing
- 이차원 배열에서 [0,0] 과 같은 표기법을 제공
- matrix일 경우, 앞은 row 뒤는 column을 의미

In [23]:
a = np.array([[1,2,3],[4.5,5,6]], int)
print(a)

[[1 2 3]
 [4 5 6]]


In [21]:
a[0,0] = 12
print(a)

[[12  2  3]
 [ 4  5  6]]


In [22]:
a[0][0] = 5
print(a)

[[5 2 3]
 [4 5 6]]


# slicing
일부분을 가져올 때 유용함

In [24]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
a[:2:] #전체row의 2열 이상

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
a[1,1:3] #row는 첫번째, column은 1열,2열에 있는 데이터

array([7, 8])

# arange
array의 범위를 지정하여 값의 list를 생성

In [26]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
np.arange(0,5,0.5)  #floating point 표시

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [29]:
np.arange(30).reshape(5,6)   #30까지 해서 reshape

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

# ones, zeros and empty
- zeros - 0으로 가득찬 ndarray  
- ones - 1으로 가득찬 ndarray
- empty - shape만 주어지고 비어있는 ndarray생성

In [30]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [32]:
np.zeros((2,5))    #2x5 matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.empty(shape=(10,), dtype=np.int8)
#메모리 공간만 딱 잡아줌 - 숫자 초기화 안시키면 이상한 값이 나올 때도,,,

array([  64,  -90,   85,    3,    0,    0,    0,    0,  -64, -117],
      dtype=int8)

# something_like
shape이 같은 크기의 1,0,empty array 반환

In [35]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

# identity
단위행렬(i행렬) 생성

In [36]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [37]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# eye
대각선이 1인 행렬

In [38]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [39]:
np.eye(3,5,k=2)  # k=시작 인덱스

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# diag
대각행렬의 값을 추출

In [40]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [41]:
np.diag(matrix, k=1)  #k:시작인덱스

array([1, 5])

# random sampling
데이터 분포에 따른 샘플링으로 array 생성

In [45]:
np.random.uniform(0,1,10).reshape(2,5)   #0~1까지 랜덤으로 10개
#균등분포

array([[0.93433405, 0.30320412, 0.22740296, 0.94110215, 0.14780162],
       [0.53249947, 0.97236663, 0.29163038, 0.46908845, 0.71309475]])

In [44]:
np.random.normal(0,1,10).reshape(2,5)
#정규분포

array([[ 0.22691978,  0.53704682,  1.2659399 ,  1.15982988, -1.3965018 ],
       [ 1.30272166, -1.83295629, -0.96721702, -1.37804553,  1.05590292]])

# sum
ndarray의 element들 간의 합

In [46]:
test_array = np.arange(1,11)
print(test_array)

test_array.sum(dtype=np.float)

[ 1  2  3  4  5  6  7  8  9 10]


55.0

In [51]:
test_array = np.arange(1,13).reshape(3,4)
print(test_array)

test_array.sum(axis=1), test_array.sum(axis=0) 
#axis : 기준이 되는 dimension축

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(array([10, 26, 42]), array([15, 18, 21, 24]))

# concatenate
Numpy array를 합치는 함수

In [3]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

# Operations b/t arrays
Numpy는 array간의 기본적인 사칙 연산을 지원함

In [4]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [6]:
test_a + test_a
#matrix + matrix  #차, 곱 다 됨

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

# transpose
transpose 또는 T attribute 사용

In [7]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
test_a.T.dot(test_a) #matrix간 곱셈

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

#broadcasting
shape이 다른 배열 간 연산을 지원하는 기능 - matrix에 모두 3을 더한다. 이런거

In [11]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [12]:
test_matrix ** scalar

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

# Numpy performance #1

In [15]:
def sclar vector_product(scalar, vector):
  result = []
  for value in vector:
    result.append(scalar*value)
  return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

%timeit sclar vector product(scalar, vector)  #for loop을 이용한 성능
%timeit [scalar * value for value in range(iternation man)]   #list cmoprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar  #numpy를 이용한 성능

SyntaxError: ignored

**왜 안되는지 모르겠음 ㅠㅠ

# Numpy performance #2
- 일반적으로 속도 : for loop < ist comprehension < numpy
- numpy : C로 구현됨 -> 성능을 확보하는 대신 dynamic typing 포기
- 대용량 계산에서 주로 사용

# comparisons

# all & any

In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a>5   #즁요~!

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [18]:
np.any(a>5), np.any(a<0) #하나라도 만족되면 false

(True, False)

In [19]:
np.all (a>5), np.all(a<10) #모두 만족되야 true

(False, True)

In [20]:
a = np.array([1,3,0], float)
np.logical_and(a>0, a<3) #and 조건의 condition

array([ True, False, False])

In [22]:
b = np.array([True, False, True], bool)
np.logical_not(b)  #not 조건의 condition -> 반대로

array([False,  True, False])

In [23]:
c = np.array([False, True, False], bool)
np.logical_or(b,c)  #or 조건의 condition

array([ True,  True,  True])

# np.where
이 조건을 만족하는 인덱스 값을 뱉어냄

In [26]:
np.where(a > 0,3,2)

array([3, 3, 2])

In [25]:
np.where(a>0)

(array([0, 1]),)

# argmax & argmin
argument의 최대 최소값

In [27]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [29]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)
#행을 기준으로 가장 큰 값의 인덱스들, 열을 기준으로 가장 작은 값의 인덱스들

(array([3, 1, 1]), array([0, 0, 2, 2]))

# boolean index
특정 조건에 따른 값을 배열 형태로 추출

In [30]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [31]:
test_array[test_array > 3]  #조건이 True인 index의 element만 추출

array([4., 8., 9., 7.])

In [32]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

# fancy index
numpy의 array를 인덱스로 추출

In [33]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int)
a[b]   #bracket index. b배열의 값을 인덱스로 해서 a값 추출

array([2., 2., 4., 8., 6., 4.])

In [34]:
a.take(b)  #bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

# numpy object - npy
numpy object(pickle)형태로 데이터를 저장하고 불러옴

In [35]:
np.save("np_test", arr=a_int) #npy형태로 저장 - pickle

NameError: ignored

In [36]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

FileNotFoundError: ignored

**왜 에러나지?ㅠ

# Pandas

In [1]:
import pandas as pd #라이브러리 호출

In [2]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
#데이터 url = './housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header = None)

In [3]:
df_data.head() #처음 다섯줄

0     1     2   3      4      5   ...  8      9     10      11    12    13
0  0.00632  18.0  2.31   0  0.538  6.575  ...   1  296.0  15.3  396.90  4.98  24.0
1  0.02731   0.0  7.07   0  0.469  6.421  ...   2  242.0  17.8  396.90  9.14  21.6
2  0.02729   0.0  7.07   0  0.469  7.185  ...   2  242.0  17.8  392.83  4.03  34.7
3  0.03237   0.0  2.18   0  0.458  6.998  ...   3  222.0  18.7  394.63  2.94  33.4
4  0.06905   0.0  2.18   0  0.458  7.147  ...   3  222.0  18.7  396.90  5.33  36.2

[5 rows x 14 columns]

In [4]:
df_data.columns = [
                   'CRIM', 'ZN', 'INDUS', "CHAS", "NOX", "RM", "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B", "LSTAT", "MEDV"]
                   #column header 이름
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31     0  0.538  ...  296.0     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242.0     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242.0     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222.0     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222.0     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [5]:
df_data.values

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

# Series
column vector를 표현하는 object

In [6]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [7]:
list_data = [1,2,3,4,5]
example_obj = Series(data = list_data)
example_obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
list_data = [1,2,3,4,5]
list_name = ["a", "b", "c", "d", "e"]
example_obj = Series(data = list_data, index = list_name)
example_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
dict_data = {"a":1, "b":2, "c":3, "d":4, "e":5}
example_obj = Series(dict_data, dtype=np.float32, name="example_data")
example_obj

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32

In [13]:
example_obj["a"]

1.0

In [14]:
example_obj["a"] = 3.2
example_obj

a    3.2
b    2.0
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32

In [15]:
example_obj.values

array([3.2, 2. , 3. , 4. , 5. ], dtype=float32)

In [16]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [17]:
example_obj.name = "number"
example_obj.index.name = "alphabet"
example_obj

alphabet
a    3.2
b    2.0
c    3.0
d    4.0
e    5.0
Name: number, dtype: float32

# DataFrame

In [18]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [20]:
DataFrame()

Empty DataFrame
Columns: []
Index: []

In [22]:
raw_data = {"first_name":["Jason", "Molly", "Tina", "jake", "Amy"],
            "last_name":["Miller", "Jacobson", "Ali", "Milner", "Cooze"],
            "age":[42,52,36,24,73],
            "city":["San Francisco", "Baltimore", "Miami", "Douglas", "Boston"]}
df = pd.DataFrame(raw_data, columns = ["first_name", "last_name", "age", "city"])
df

first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

column 선택

In [23]:
DataFrame(raw_data, columns = ["age", "city"])

age           city
0   42  San Francisco
1   52      Baltimore
2   36          Miami
3   24        Douglas
4   73         Boston

새로운 column 추가

In [24]:
DataFrame(raw_data, columns = ["first_name", "last_name", "age", "city", "debt"])

first_name last_name  age           city debt
0      Jason    Miller   42  San Francisco  NaN
1      Molly  Jacobson   52      Baltimore  NaN
2       Tina       Ali   36          Miami  NaN
3       jake    Milner   24        Douglas  NaN
4        Amy     Cooze   73         Boston  NaN

값은 NaN(Not a Number)로 출력됨

column 선택해서 series 추출

In [25]:
df = DataFrame(raw_data, columns = ["first_name", "last_name", "age", "city", "debt"])
df.first_name

0    Jason
1    Molly
2     Tina
3     jake
4      Amy
Name: first_name, dtype: object

In [26]:
df["first_name"]

0    Jason
1    Molly
2     Tina
3     jake
4      Amy
Name: first_name, dtype: object

In [27]:
df

first_name last_name  age           city debt
0      Jason    Miller   42  San Francisco  NaN
1      Molly  Jacobson   52      Baltimore  NaN
2       Tina       Ali   36          Miami  NaN
3       jake    Milner   24        Douglas  NaN
4        Amy     Cooze   73         Boston  NaN

loc - index location, iloc - index position

In [28]:
df.loc[1]

first_name        Molly
last_name      Jacobson
age                  52
city          Baltimore
debt                NaN
Name: 1, dtype: object

In [29]:
df["age"].iloc[1:]

1    52
2    36
3    24
4    73
Name: age, dtype: int64

In [30]:
s = pd.Series(np.nan, index=[49,48,47,46,45,1,2,3,4,5])
s.loc[:3]

49   NaN
48   NaN
47   NaN
46   NaN
45   NaN
1    NaN
2    NaN
3    NaN
dtype: float64

In [31]:
s.iloc[:3]

49   NaN
48   NaN
47   NaN
dtype: float64

In [32]:
df.age > 40

0     True
1     True
2    False
3    False
4     True
Name: age, dtype: bool

column에 새로운 데이터 할당

In [33]:
df.debt = df.age > 40
df

first_name last_name  age           city   debt
0      Jason    Miller   42  San Francisco   True
1      Molly  Jacobson   52      Baltimore   True
2       Tina       Ali   36          Miami  False
3       jake    Milner   24        Douglas  False
4        Amy     Cooze   73         Boston   True

In [35]:
df.T   #transpose

0          1      2        3       4
first_name          Jason      Molly   Tina     jake     Amy
last_name          Miller   Jacobson    Ali   Milner   Cooze
age                    42         52     36       24      73
city        San Francisco  Baltimore  Miami  Douglas  Boston
debt                 True       True  False    False    True

In [36]:
df.values  #값 출력

array([['Jason', 'Miller', 42, 'San Francisco', True],
       ['Molly', 'Jacobson', 52, 'Baltimore', True],
       ['Tina', 'Ali', 36, 'Miami', False],
       ['jake', 'Milner', 24, 'Douglas', False],
       ['Amy', 'Cooze', 73, 'Boston', True]], dtype=object)

In [37]:
df.to_csv()    #csv 변환

',first_name,last_name,age,city,debt\n0,Jason,Miller,42,San Francisco,True\n1,Molly,Jacobson,52,Baltimore,True\n2,Tina,Ali,36,Miami,False\n3,jake,Milner,24,Douglas,False\n4,Amy,Cooze,73,Boston,True\n'

In [38]:
del df["debt"]  #column 삭제
df

first_name last_name  age           city
0      Jason    Miller   42  San Francisco
1      Molly  Jacobson   52      Baltimore
2       Tina       Ali   36          Miami
3       jake    Milner   24        Douglas
4        Amy     Cooze   73         Boston

# Selection and Drop

In [2]:
import pandas as pd

In [4]:
!conda install --y xlrd

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\82103\Anaconda3

  added / updated specs:
    - xlrd


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _anaconda_depends-5.3.1    |           py37_0           5 KB
    anaconda-custom            |           py37_1           2 KB
    appdirs-1.4.4              |             py_0          13 KB
    automat-20.2.0             |             py_0          31 KB
    bcrypt-3.1.6               |   py37he774522_0         164 KB
    blaze-0.11.3               |           py37_0         624 KB
    ca-certificates-2021.1.19  |       haa95532_0         160 KB
    certifi-2020.12.5          |   py37haa95532_0         144 KB
    constantly-15.1.0          |   py37h28b3542_0          13 KB
    datashape-0.5.4            |           py37_1         100 KB
    flask-cors-3.0.10          |     pyhd3eb1b0_0        


The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/win-64::anaconda==2019.03=py37_0
  - defaults/win-64::numba==0.43.1=py37hf9181ef_0


In [41]:
import numpy as np
df = pd.read_excel("C:/Users/82103/Desktop/excel-comp-data.xlsx")
df.head()

account                         name                                street  \
0   211829   Kerluke, Koepp and Hilpert                    34456 Sean Highway   
1   320563               Walter-Trantow                     1311 Alvis Tunnel   
2   648336   Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
3   109996  D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
4   121213                Bauch-Goldner                   7274 Marissa Common   

              city          state  postal-code     Jan     Feb    Mar  
0       New Jaycob          Texas        28752   10000   62000  35000  
1    Port Khadijah  NorthCarolina        38365   95000   45000  35000  
2   New Lilianland           Iowa        76517   91000  120000  35000  
3       Hyattburgh          Maine        46021   45000  120000  10000  
4  Shanahanchester     California        49681  162000  120000  35000

In [42]:
df["account"].head(3)

0    211829
1    320563
2    648336
Name: account, dtype: int64

In [43]:
df[["account", "street", "state"]].head(3)

account                                street          state
0   211829                    34456 Sean Highway          Texas
1   320563                     1311 Alvis Tunnel  NorthCarolina
2   648336  62184 Schamberger Underpass Apt. 231           Iowa

In [44]:
df[:10]

account                              name  \
0   211829        Kerluke, Koepp and Hilpert   
1   320563                    Walter-Trantow   
2   648336        Bashirian, Kunde and Price   
3   109996       D'Amore, Gleichner and Bode   
4   121213                     Bauch-Goldner   
5   132971  Williamson, Schumm and Hettinger   
6   145068                        Casper LLC   
7   205217                  Kovacek-Johnston   
8   209744                    Champlin-Morar   
9   212303                    Gerhold-Maggio   

                                 street               city          state  \
0                    34456 Sean Highway         New Jaycob          Texas   
1                     1311 Alvis Tunnel      Port Khadijah  NorthCarolina   
2  62184 Schamberger Underpass Apt. 231     New Lilianland           Iowa   
3           155 Fadel Crescent Apt. 144         Hyattburgh          Maine   
4                   7274 Marissa Common    Shanahanchester     California   
5                  89403 Casimer Spring       Jeremieburgh       Arkansas   
6          340 Consuela Bridge Apt. 400  Lake Gabriellaton     Mississipi   
7          91971 Cronin Vista Suite 601         Deronville    RhodeIsland   
8                      26739 Grant Lock    Lake Juliannton   Pennsylvania   
9             366 Maggio Grove Apt. 998          North Ras          Idaho   

   postal-code     Jan     Feb    Mar  
0        28752   10000   62000  35000  
1        38365   95000   45000  35000  
2        76517   91000  120000  35000  
3        46021   45000  120000  10000  
4        49681  162000  120000  35000  
5        62785  150000  120000  35000  
6        18008   62000  120000  70000  
7        53461  145000   95000  35000  
8        64415   70000   95000  35000  
9        46308   70000  120000  35000

In [45]:
df["name"][:3]

0    Kerluke, Koepp and Hilpert
1                Walter-Trantow
2    Bashirian, Kunde and Price
Name: name, dtype: object

In [46]:
account_serires = df["account"]
account_serires[:3]

0    211829
1    320563
2    648336
Name: account, dtype: int64

In [47]:
account_serires[[1,5,2]]

1    320563
5    132971
2    648336
Name: account, dtype: int64

In [48]:
account_serires[account_serires<250000]

0     211829
3     109996
4     121213
5     132971
6     145068
7     205217
8     209744
9     212303
10    214098
11    231907
12    242368
Name: account, dtype: int64

In [49]:
df.index = df["account"]

In [50]:
df.head()

account                         name  \
account                                         
211829    211829   Kerluke, Koepp and Hilpert   
320563    320563               Walter-Trantow   
648336    648336   Bashirian, Kunde and Price   
109996    109996  D'Amore, Gleichner and Bode   
121213    121213                Bauch-Goldner   

                                       street             city          state  \
account                                                                         
211829                     34456 Sean Highway       New Jaycob          Texas   
320563                      1311 Alvis Tunnel    Port Khadijah  NorthCarolina   
648336   62184 Schamberger Underpass Apt. 231   New Lilianland           Iowa   
109996            155 Fadel Crescent Apt. 144       Hyattburgh          Maine   
121213                    7274 Marissa Common  Shanahanchester     California   

         postal-code     Jan     Feb    Mar  
account                                      
211829         28752   10000   62000  35000  
320563         38365   95000   45000  35000  
648336         76517   91000  120000  35000  
109996         46021   45000  120000  10000  
121213         49681  162000  120000  35000

In [51]:
del df["account"]
df.head()

name                                street  \
account                                                                      
211829    Kerluke, Koepp and Hilpert                    34456 Sean Highway   
320563                Walter-Trantow                     1311 Alvis Tunnel   
648336    Bashirian, Kunde and Price  62184 Schamberger Underpass Apt. 231   
109996   D'Amore, Gleichner and Bode           155 Fadel Crescent Apt. 144   
121213                 Bauch-Goldner                   7274 Marissa Common   

                    city          state  postal-code     Jan     Feb    Mar  
account                                                                      
211829        New Jaycob          Texas        28752   10000   62000  35000  
320563     Port Khadijah  NorthCarolina        38365   95000   45000  35000  
648336    New Lilianland           Iowa        76517   91000  120000  35000  
109996        Hyattburgh          Maine        46021   45000  120000  10000  
121213   Shanahanchester     California        49681  162000  120000  35000

In [52]:
df[["name","street"]][:2]

name              street
account                                                
211829   Kerluke, Koepp and Hilpert  34456 Sean Highway
320563               Walter-Trantow   1311 Alvis Tunnel

In [53]:
df.loc[[211829, 320563],["name","street"]]

name              street
account                                                
211829   Kerluke, Koepp and Hilpert  34456 Sean Highway
320563               Walter-Trantow   1311 Alvis Tunnel

In [54]:
df[["name","street"]].iloc[:10]

name  \
account                                     
211829         Kerluke, Koepp and Hilpert   
320563                     Walter-Trantow   
648336         Bashirian, Kunde and Price   
109996        D'Amore, Gleichner and Bode   
121213                      Bauch-Goldner   
132971   Williamson, Schumm and Hettinger   
145068                         Casper LLC   
205217                   Kovacek-Johnston   
209744                     Champlin-Morar   
212303                     Gerhold-Maggio   

                                       street  
account                                        
211829                     34456 Sean Highway  
320563                      1311 Alvis Tunnel  
648336   62184 Schamberger Underpass Apt. 231  
109996            155 Fadel Crescent Apt. 144  
121213                    7274 Marissa Common  
132971                   89403 Casimer Spring  
145068           340 Consuela Bridge Apt. 400  
205217           91971 Cronin Vista Suite 601  
209744                       26739 Grant Lock  
212303              366 Maggio Grove Apt. 998

# lambda

In [6]:
import pandas as pd
import numpy as np

In [7]:
from pandas import Series

In [8]:
f = lambda x,y: x+y
f(1,4)

5

In [9]:
def f(x,y):
    return x+y

In [10]:
f=lambda x : x**2
f(3)

9

In [11]:
f = lambda x : x+5
f(3)

8

In [13]:
(lambda x : x+1)(5)

6

# map & replace

In [14]:
ex = [1,2,3,4,5]
f = lambda x : x**2
list(map(f, ex))

[1, 4, 9, 16, 25]

In [15]:
f = lambda x, y : x+y
list(map(f, ex, ex))

[2, 4, 6, 8, 10]

In [16]:
list(map(lambda x : x+5, ex))

[6, 7, 8, 9, 10]

In [26]:
s1 = Series(np.arange(10))
s1.head(5)

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [27]:
s1.map(lambda x: x**2).head(5)

0     0
1     1
2     4
3     9
4    16
dtype: int64

In [28]:
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [29]:
z = {1: "A", 2: "B", 3: "C"}
s1.map(z)

0    NaN
1      A
2      B
3      C
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
dtype: object

In [30]:
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

## 

In [32]:
s2 = Series(np.arange(10,20))
s1.map(s2)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int32

In [33]:
s2

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int32

In [36]:
!pip install wget

  Stored in directory: C:\Users\82103\AppData\Local\pip\Cache\wheels\40\15\30\7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget


In [38]:
!wget https://raw.githubusercontent.com/rstudio/Intro/master/data/wages.csv

'wget'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [39]:
yum install -y wget.x86_64

SyntaxError: invalid syntax (<ipython-input-39-9a4b3af69e9b>, line 1)

# apply & applymap

In [40]:
df = pd.read_csv("wages.csv")
df.head()

FileNotFoundError: [Errno 2] File b'wages.csv' does not exist: b'wages.csv'