# 머신러닝의 학습 방법들

# 목표 : 예측 함수와 실제 값의 오차를 줄여보자!

# GRADIENT DESCENT BASED LEARNING
실제 값과 학습된 모델 예측치의 오차 최소화. 적당한 모델 파라미터 찾는 것

y=ax+b에서 a,b의 값
- 예측함수 : 가설함수라고 부름 f(x) = h(x) 
- 실제값과 가설함수의 차이 : cost function ,J(w0, w1)
- Cost function에서 구하는 것 : cost function의 '최소화'를 위한 weight 값

# Normal equation
- X^TX의 역행렬이 존재할 때 사용
- Iteration 등 사용자 지정 파라미터가 없음 
- Feature가 많으면 계산 속도가 느려짐

In [16]:
class LinearRegression(object):
  def __init__(self, fit_intercept=True, copy_X = True):
    self.fit_intercept = fit_intercept
    self.copy_X = cop_X

    self._coef = None
    self._intercept = None
    self._new_X = None

  def fit(self, X, y):  #X,y의 데이터가 입력되면 normal equation값을 가지고 weight값을 찾아내는 함수
    pass
  
  def predict(self, X):   #실험하고자 하는 X값을 넣었을 때 y예측값을 반환
    pass

  @property
  def coef(self):   #coef라는 이름으로 리턴
    return self._coef   #p=[w1, ..., wn]까지 리턴

  @property
  def intercept(self):   #intercept로 리턴. intercept=w0
    return self._intercept  #접근x 

In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("./test.csv")
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [14]:
x = df["x"].values.reshape(-1,1)
y = df["y"].values

# Build model
모듈 이름

In [60]:
"""
import normal_equation_lr as linear_model
import imp
imp.reload(linear_model)
"""

'\nimport normal_equation_lr as linear_model\nimport imp\nimp.reload(linear_model)\n'

In [10]:
import solution_linear_model as linear_model
import imp
imp.reload(solution_linear_model)

<module 'solution_linear_model' from 'C:\\Users\\82103\\Desktop\\부트코스-머신러닝을 위한 파이썬\\solution_linear_model.py'>

In [11]:
lr = linear_model.LinearRegression(fit_intercept=True)

In [23]:
x.shape #데이터 300개.

(300, 1)

In [24]:
y.shape

(300,)

In [41]:
lr.fit(x,y)

ValueError: shapes (2,300) and (54,1) not aligned: 300 (dim 1) != 54 (dim 0)

In [21]:
lr.intercept #fitting해준 후에만 나옴

-0.46181077366111367

In [25]:
lr.coef  #얘도

array([1.01433536])

In [26]:
lr.predict(x)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

In [39]:
class LinearRegression(object):
  def __init__(self, fit_intercept=True, copy_X = True):  #copy_X = defaul valiable. 나머지는 default로 처리됨
    self.fit_intercept = fit_intercept
    self.copy_X = cop_X

    self._coef = None
    self._intercept = None
    self._new_X = None
    
    def fit(self, X, y):
        self._new_X = np.array(X)
        y = y.reshape(-1, 1)
        
        if self.fit_intercept: #절편추가
            intercept_vector = np.ones([len(self._new_X), 1])
            self._new_X = np.concatenate(  #두개값 붙일 때
                (intercept_vector, self._new_X), axis=1)
            
        weights = np.linalg.inv( #역함수 구해주는 넘파이 함수
            self._new_T.dot(self._new_X)).dot(  #X의 transpose에 X구해서 역함수 하고 XT dot y
                                        self._new_X.T.dot(y)).flatten()  #계산 편의 - flatten
        
        if self.fit_intercept:
            self._intercept = weights[0] #w0
            self._coef = weights[1:] #w1, w2, ..., wn
        else:
            self._coef = weights
            
    #def predict(self, X)

# Load dataset - multiple variables

In [32]:
df = pd.read_csv("./mlr09.csv")
df.head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  average_points_scored  
0                              0.672                    9.2  
1                              0.797                   11.7  
2                              0.761                   15.8  
3                              0.651                    8.6  
4                              0.900                   23.2

In [33]:
y = df["average_points_scored"].values #y값을 따로 빼서

In [47]:
df.iloc[:,:-1].head() #x값만 뽑아서 매트릭스 X 로 만듦

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  
0                              0.672  
1                              0.797  
2                              0.761  
3                              0.651  
4                              0.900

In [48]:
X = df.iloc[:,:-1].values

In [49]:
X[:5]

array([[  6.8  , 225.   ,   0.442,   0.672],
       [  6.3  , 180.   ,   0.435,   0.797],
       [  6.4  , 190.   ,   0.456,   0.761],
       [  6.2  , 180.   ,   0.416,   0.651],
       [  6.9  , 205.   ,   0.449,   0.9  ]])

# Rescaled - 해도되고 안해도 됨

In [50]:
mu_X = np.mean(X, axis=0)
std_X = np.std(X, axis=0)

rescaled_X = (X - mu_X) / std_X

In [51]:
rescaled_X[:5]

array([[ 0.46843663,  0.50336336, -0.12692668, -0.70404955],
       [-0.63137111, -0.99746237, -0.25187012,  0.55584824],
       [-0.41140956, -0.66394554,  0.12296022,  0.19299768],
       [-0.85133266, -0.99746237, -0.59100234, -0.91571238],
       [ 0.68839818, -0.1636703 , -0.00198323,  1.59400403]])

# Validation

In [61]:
from sklearn import linear_model
sk_lr = linear_model.LinearRegression(normalize=False)
sk_lr.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [52]:
lr.fit(rescaled_X, y)

In [53]:
lr.coef

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [54]:
lr.intercept

11.790740740740738

In [62]:
sk_lr.fit(rescaled_X, y) #사이킷런 lr로 돌리는거랑 비교

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [64]:
sk_lr.coef_

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [65]:
sk_lr.intercept_

11.790740740740736

# Gradient Descent

컴퓨터에 x^2의 최적값 찾기
- gradient를 구하고 얼마만큼 내려가는지 (running rate)를 곱함

NameError: name 'random' is not defined